datasets:
  basedir: /home/data/kaggle_data/myllia/
  means:        /home/data/kaggle_data/myllia/training_data_means.csv
  pert_ids_val: /home/data/kaggle_data/myllia/pert_ids_val.csv
  myllia: /home/data/kaggle_data/myllia/training_cells.h5ad
  vcc: /home/data/single_cell/vcc_2025/adata_Training.h5ad
  jiang_TGFB: /home/data/single_cell/vcc_2025/TGFB_Perturb_seq.h5ad
  jiang_IFNB: /home/data/single_cell/vcc_2025/IFNB_Perturb_seq.h5ad
  jiang_IFNG: /home/data/single_cell/vcc_2025/IFNG_Perturb_seq.h5ad
  reactome: 

ml:
  d_model: 512
  nhead: 8
  dim_feedforward: 2048
  dropout: 0.1
  num_layers: 4
  # output_dim: 128
  # max_seq_len: 2000
  batch_size: 16
  lr: 0.0001
  epochs: 20