datasets:
  means: /home/data/kaggle_data/myllia/training_data_means.csv
  pert_ids_val: /home/data/kaggle_data/myllia/pert_ids_val.csv
  myllia: /home/data/kaggle_data/myllia/myllia.h5ad
  vcc: /home/data/single_cell/vcc_2025/vcc.h5ad
  replogle: /home/data/single_cell/Replogle_et_al/replogle.h5ad
  jiang_TGFB: /home/data/single_cell/Jiang_et_al/TGFB_Perturb_seq.h5ad
  jiang_IFNB: /home/data/single_cell/Jiang_et_al/IFNB_Perturb_seq.h5ad
  jiang_IFNG: /home/data/single_cell/Jiang_et_al/IFNG_Perturb_seq.h5ad
  reactome: 

ml:
  d_model: 512
  nhead: 8
  dim_feedforward: 2048
  dropout: 0.1
  num_layers: 4
  # output_dim: 128
  # max_seq_len: 2000
  batch_size: 16
  lr: 0.0001
  epochs: 20